# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>


development:
  adapter: sqlite3
  encoding: unicode
  database: blog_ror
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  encoding: unicode
  database: blog_ror_test
  pool: 5
  timeout: 5000
